name: Export Workspace as Dynamic Plugins Packages
on:
  workflow_call:
    inputs:
      node-version:
        description: node-version to execute the export
        type: string
        required: true

      janus-cli-version:
        description: Version of the janus-idp/cli package.
        type: string
        required: true

      upload-project-on-error:
        description: Upload the complete project as a workflow artifact in case of error in order to troubleshoot.
        required: true
        type: boolean
      
      workspace-path:
        description: Relative path of a single workspace on which the export workflow should be applied.
        required: false
        type: string
        default: ''

      overlay-branch:
        description: Branch of the overlay structure (current branch by default).
        type: string
        required: false
        default: ''

      publish-container:
        description: Publish a container image for the dynamic plugins
        required: true
        type: boolean

  workflow_dispatch:
    inputs:
      node-version:
        description: node-version to execute the export
        type: string
        required: false
        default: ''

      janus-cli-version:
        description: Version of the janus-idp/cli package.
        type: string
        required: false
        default: ''

      upload-project-on-error:
        description: Upload the complete project as a workflow artifact in case of error in order to troubleshoot.
        required: false
        type: boolean
        default: false
      
      workspace-path:
        description: Relative path of a single workspace on which the export workflow should be applied.
        required: false
        type: string

      overlay-branch:
        description: Branch of the overlay structure
        type: string
        required: true

      publish-container:
        description: Publish a container image for the dynamic plugins
        required: false
        type: boolean
        default: false   

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  parent_export:
    uses: davidfestal/rhdh-plugin-export-utils/.github/workflows/export-workspaces-as-dynamic.yaml@multi-plugins-repo
    with:
      node-version: ${{ inputs.node-version }}
      janus-cli-version: ${{ inputs.janus-cli-version }}
      upload-project-on-error: ${{ inputs.upload-project-on-error == 'true' }}
      overlay-branch: ${{ inputs.overlay-branch }}
      workspace-path: ${{ inputs.workspace-path }}
      publish-container: ${{ inputs.publish-container == 'true' }}

    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write