name: PR Actions Parse Test

on:
  workflow_dispatch:
    inputs:
      comment:
        description: "Simulated comment body"
        required: true
      expect:
        description: "Expected parsed command (optional: /publish|/update-versions|/update-commit)"
        required: false
        default: ""

jobs:
  parse:
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.extract.outputs.command }}
      command_name: ${{ steps.extract.outputs.command_name }}
    steps:
      - name: Extract command
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const raw = core.getInput('comment');
            const lines = String(raw)
              .split(/\r?\n/)
              .map(l => l.trim())
              .filter(l => l.length > 0);
            const allowed = new Set(['/publish', '/update-versions', '/update-commit']);
            const firstMatching = lines.find(l => allowed.has(l)) || '';
            core.info(`Comment body:`);
            core.info(raw);
            core.info(`Parsed lines: ${JSON.stringify(lines)}`);
            core.info(`Parsed command: ${firstMatching || '(none)'}`);
            core.setOutput('command', firstMatching);
            core.setOutput('command_name', firstMatching.startsWith('/') ? firstMatching.slice(1) : firstMatching);

  show:
    runs-on: ubuntu-latest
    needs:
      - parse
    steps:
      - name: Show parsed outputs
        run: |
          echo "command=${{ needs.parse.outputs.command }}"
          echo "command_name=${{ needs.parse.outputs.command_name }}"
          if [ -n "${{ github.event.inputs.expect }}" ] && [ "${{ github.event.inputs.expect }}" != "${{ needs.parse.outputs.command }}" ]; then
            echo "Expected '${{ github.event.inputs.expect }}' but got '${{ needs.parse.outputs.command }}'" >&2
            exit 1
          fi

