name: Update opened PRs from Release Branch
description: Update opened PRs from their target a release branch with common, non workspace content. 
on:
  workflow_call:
    inputs:
      release-branch:
        description: Release branch whose PRs should be updated with the given commit.
        type: string
        required: true
      pr:
        description: PR number of a single PR to update. By default update all PRs.
        type: string
        required: false

  workflow_dispatch:
    inputs:
      release-branch:
        description: Release branch whose PRs should be updated with the given commit.
        type: string
        required: true
      pr:
        description: PR number of a single PR to update. By default update all PRs.
        type: string
        required: false

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-prs:
    runs-on: ubuntu-latest
    name: Update PRs

    steps:
      - uses: actions/github-script@v7
        env:
          INPUT_RELEASE_BRANCH: ${{ inputs.release-branch }}      
          INPUT_PR: ${{ inputs.pr }}      
        with:
          script: |
            const script = require('./.github/workflows/github-script/update-prs-with-release-branch-commits.js');
            await script({github, context, core});